/// Flutter icons TimeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TimeIcons
///      fonts:
///       - asset: fonts/TimeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TimeIcons {
  TimeIcons._();

  static const _kFontFam = 'TimeIcons';

  static const IconData warning_icon = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData location_filled_icon = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData repeat_icon = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData location_icon = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData dm_icon = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData notifications_icon = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData search_icon = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData history_icon = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData home_icon = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData delete_icon = const IconData(0xe810, fontFamily: _kFontFam);
}
